version: "3"

services:
  app:
    container_name: book_alloc_app
    build:
      context: .
      dockerfile: build/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: make dev
    volumes:
      - ./:/src
    environment:
      TZ: Asia/Tokyo
    working_dir: /src
    ports:
      - "8888:8080"

  db:
    container_name: book_alloc_db
    image: postgres:15.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_alloc
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U user -d book_alloc || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    container_name: book_alloc_test_db
    image: postgres:15.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_alloc_test
    ports:
      - '55432:5432'
    healthcheck:
      test: "pg_isready -U user -d book_alloc_test || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: node:19.7.0
    tty: true
    volumes:
      - ../reading_experience-alloc-web:/src
    environment:
      HOST: 0.0.0.0
    working_dir: /src
    command: sh -c "yarn && yarn dev"
    ports:
      - '5173:5173'
