# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "./tmp/book-alloc"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./bin/book-alloc cmd/book-alloc/server.go"
# Binary file yields from `cmd`.
bin = "./bin/book-alloc"
# Watch these filename extensions.
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = ["vendor"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = false
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true